### ISSUE TITLE
Question about logic of synchronization and reference line toos https://github.com/cornerstonejs/cornerstoneTools/issues/1122

### ISSUE THREAD

**Issue by behnazeslami** [tunglt1810/viewer-core#2]
Hi,
Based on your issue in this link [https://github.com/cornerstonejs/cornerstoneTools/issues/1122](url) I have some questions  about reference line tools and synchronization between same dicom cuts. I used to cornerstonejs library in react and could implement synchronization but I want to know about the basic and main logic of synchronization? Also I want to implement reference line tools in my react dicom viewer project. 
Actually I read all the cornerstonejs documentation and google groups but I couldn't find any helpful link.
Do you have information about these two modules and is it possible for you to help me more in this way?

Thanks
With kind regards

**Comment by tunglt1810** [comment]
Hi @behnazeslami. 
First, you should read the source code, some features are missing on the document. 
The basic logic of synchronization tool is handle cornerstone event from source elements and update target elements after using a calculation function.
With reference line tool you need to examinate two set of enable element. The 1st one is source element, which is the current active viewport. The second set is target elements, aka another enabled element.
You need create a ReferenceLine Synchonizer
```
const referenceLinesSynchronizer = new cornerstoneTools.Synchronizer(
        // Cornerstone event that should trigger synchronizer
        cornerstone.EVENTS.NEW_IMAGE,
        // Logic that should run on target elements when event is observed on source elements
        cornerstoneTools.updateImageSynchronizer
    );
```
So now, you need to add the current active viewport to the source element
referenceLinesSynchronizer.addSource(...)
and referenceLinesSynchronizer.addTarget([...other enabled viewport])
